### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by sujanme25** [hungchun-lin/Stock-price-prediction-using-GAN-Capstone-Group1#1]
Getting error in training. with 8 dimension and 17 features.
 <ipython-input-81-e7675e10209c>:34 train_step  *
        real_y_reshape = tf.reshape(real_y, [real_y.shape[0], real_y.shape[1],1])
    C:\Users\sujan\anaconda3\lib\site-packages\tensorflow\python\framework\tensor_shape.py:887 __getitem__
        return self._dims[key].value

    IndexError: list index out of range

**Comment by hungchun-lin** [comment]
@sujanme25  You can retry the code now, it was in the developing process, so might not have some mistake.
