### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Rajmehta123** [hungchun-lin/Stock-price-prediction-using-GAN-Capstone-Group1#5]
Amazing project. Thanks for the effort. Files are missing, for eg; train_predict_index.npy, test_predict_index.npy

```
train_predict_index = np.load("train_predict_index.npy", allow_pickle=True)
test_predict_index = np.load("test_predict_index.npy", allow_pickle=True)
```

In the prediction, the model file is missing: gen_GRU_model_89.h5

`G_model = tf.keras.models.load_model('gen_GRU_model_89.h5')
`

Really appreciate it if you could upload them. Thanks. :)

**Comment by hungchun-lin** [comment]
I don't think we use the file name as "train_predict_index" anymore, it should be 'index_train.npy' and 'index_test.npy', and you will get the index files while you run the code "2. data_preprocessing.py".

**Comment by Rajmehta123** [comment]
Okay. Thank you.

And the model file? Will that generate after training? I couldn't find the code where you were saving the model as 'gen_GRU_model_89'

**Comment by Rajmehta123** [comment]
Generated them. Thanks.
