### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by CrimsonCyborg** [hungchun-lin/Stock-price-prediction-using-GAN-Capstone-Group1#6]
Because there is no comment, I want to ask where there is a train_ predict_ index.npy?

**Comment by N3KRoN** [comment]
This https://github.com/hungchun-lin/Stock-price-prediction-using-GAN/blob/78265172e41468e431f846e4eaa588b4c4c7a459/Code/2.%20data_preprocessing.py#L118-L125

**Comment by hungchun-lin** [comment]
Please see: https://github.com/hungchun-lin/Stock-price-prediction-using-GAN/issues/5
